// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCEFAV3gJ0fbOgt2LxyuRR__Iu6PqtSZ4',
    appId: '1:63892927784:web:9650f7963c45abaeb38c1d',
    messagingSenderId: '63892927784',
    projectId: 'flutterchatapp-d7d1e',
    authDomain: 'flutterchatapp-d7d1e-d3e5a.firebaseapp.com',
    storageBucket: 'flutterchatapp-d7d1e.appspot.com',
    measurementId: 'G-7B6M7T5EJG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDmWFWheiq1RN589CujLB1wLXmTccAebs',
    appId: '1:63892927784:android:178a29d2532ef62fb38c1d',
    messagingSenderId: '63892927784',
    projectId: 'flutterchatapp-d7d1e',
    storageBucket: 'flutterchatapp-d7d1e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKD8ZcFFhyZl0U44JCGzVdfc4CiVnCfP0',
    appId: '1:63892927784:ios:1c11db5823680a71b38c1d',
    messagingSenderId: '63892927784',
    projectId: 'flutterchatapp-d7d1e',
    storageBucket: 'flutterchatapp-d7d1e.appspot.com',
    iosBundleId: 'com.josegalvez.chatapp',
  );
}
